CREATE TABLE IF NOT EXISTS pickles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS cart (
    CID INT AUTO_INCREMENT PRIMARY KEY,
    ID INT NOT NULL,
    PID INT NOT NULL,
    QTY INT NOT NULL,
    FOREIGN KEY (ID) REFERENCES users(ID),
    FOREIGN KEY (PID) REFERENCES pickles(PID)
);